version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - HOME=/tmp
      - USER=root
    volumes:
      - ./spark:/opt/spark/work
    depends_on:
      - kafka

  api:
    build: ./api
    ports:
      - "8000:8000"
      - "8888:8888"
    depends_on:
      - spark
